In [1]:
import numpy as np

In [3]:
X = np.random.normal(loc=1,scale=10,size=(1000,50))
X

array([[ 10.93612636,  -1.8129417 , -18.75120066, ...,  -8.50651539,
         11.52784056,  -4.68284571],
       [ -6.11324026,   8.70213276,   2.6801021 , ..., -12.10686198,
         10.55793798,  -0.8376656 ],
       [ -0.39591245,   5.97208609, -15.41742813, ...,  19.65848964,
         -6.04224197, -24.47304125],
       ...,
       [-18.07897365,   6.07997887,  -7.58386581, ...,  13.73577177,
         -9.6693445 ,   1.07351034],
       [-24.77619954,  15.52276195,   6.85446532, ...,  -7.96330623,
          3.76507829,   9.52139911],
       [  4.47141887,   5.5984222 ,  -6.52298735, ...,   1.60382752,
          0.3942361 ,   2.19695408]])

In [5]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
X_norm

array([[ 0.98468197, -0.2228539 , -1.98590459, ..., -0.9281154 ,
         1.08291297, -0.56286187],
       [-0.7752673 ,  0.84550338,  0.14892246, ..., -1.2853238 ,
         0.985044  , -0.17010409],
       [-0.18508661,  0.56812396, -1.65381895, ...,  1.86627568,
        -0.69001346, -2.5842895 ],
       ...,
       [-2.01045006,  0.57908613, -0.87349771, ...,  1.27865321,
        -1.0560098 ,  0.02510893],
       [-2.70178235,  1.53849599,  0.56474149, ..., -0.8742209 ,
         0.29960382,  0.88800065],
       [ 0.31735177,  0.5301588 , -0.76782089, ...,  0.07498231,
        -0.04053432,  0.13986072]])

In [10]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
np.nonzero((np.sum(Z,axis=1))>10)

(array([1, 4, 5], dtype=int64),)

In [11]:
A = np.eye(3)
B = np.eye(3)

In [13]:
AB = np.vstack((A, B))
AB

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])